#!/bin/bash

# A simple tee in pure bash 
# Implement reopen files

SELF="${BASH_SOURCE[0]##*/}"

OPTS="d:p:i:s:h"
USAGE="Usage: $SELF [$OPTS] FILE1 FILE2 ..."

HELP="
$USAGE

    Options:
        add:
            -d          Description
            -p          priority (high,medium,low)
            -i          Force id
        edit:
            -i          id
            -p          priority
            -d          Description
        done:
            -i          id
        ongoing:
            -i          id
        show:
            -i          id
        list:
            Default: Id orders from high priority to low, and from ongoing to created (Done will not be listed only if set)
            -p          Priority
            -s          state (done,ongoing,done)
        remove:
            -i          id

        -h      Help

    Environment Variables:
        NO_COLOR
        TODO_WORKINGDIR

    About
        This script will create the following directory tree:
            HOME/$SELF/{created,done,ongoing}/{1-9}/ID/{description,content}
"

: "${TODO_WORKINGDIR:=$HOME/.$SELF}"
TODO_WORKINGDIR="${TODO_WORKINGDIR%/}"

declare -A color=(
    [high]='\033[31m'
    [medium]='\033[33m'
    [low]='\033[32m'
)

[[ -z "$NO_COLOR" ]] || declare -A color=([high]="" [medium]="" [low]="")    

tempFiles=()

_quit(){
    local retCode="$1" msg="${*:2}"

    printf '%s\n' "$msg"
    exit "$retCode"
}

_find(){
    local _dir _id
    [[ -z "$1" ]] && return 1
    shopt -s extglob
    for _dir in "$TODO_WORKINGDIR"/{created,done,ongoing}/*/*; do
        _id="${_dir##*/}"
        [[ "$_id" == "$1" ]] && { printf '%s' "$_dir"
            return
        }
    done

    return 1
}

_mktemp(){
    local tmpFile
    tmpFile="$(mktemp "${TMPDIR:-/tmp}/$SELF.XXXXXXXXXXX")"
    tempFiles+=("$tmpFile")
    printf '%s' "$tmpFile"    
}

_parse(){
    IFS='/' read -r state priority id <<<"${1#$TODO_WORKINGDIR/}"
}

_exit(){
    for file in "${tempFiles[@]}"; do
        rm "$file"
    done
}

_priorityCheck(){
    case "$1" in
        high|medium|low)        return                          ;;
        *)                      _quit 2 "Priority not ok! $HELP";;
    esac   
}

add(){
    for value in "description"; do
        [[ -z "${!value}" ]] && _quit 2 "$value is not defined!\n $HELP"
    done

    : "${priority:=low}"

    _priorityCheck "$priority"

    mkdir -p "$TODO_WORKINGDIR" &>/dev/null
    [[ -f "$TODO_WORKINGDIR/lastId" ]] || printf '0' > "$TODO_WORKINGDIR/lastId"
    [[ -z "$id" ]] && { ((id=$(<"$TODO_WORKINGDIR/lastId") + 1 ))
        overrideLastId=1
    }

    [[ -d "$TODO_WORKINGDIR/created/$priority/$id" ]] || mkdir -p "$TODO_WORKINGDIR/created/$priority/$id"
    printf '%s' "$description" > "$TODO_WORKINGDIR/created/$priority/$id/description"

    ${EDITOR:-vi} "$TODO_WORKINGDIR/created/$priority/$id/content"

    (( overrideLastId )) && printf '%s' "$id" > "$TODO_WORKINGDIR/lastId"
}

list(){
    [[ -z "${state[*]}" ]] && state=("ongoing" "created")    
    [[ -z "${priority[*]}" ]] && priority=("high" "medium" "low")

    shopt -s extglob
    shopt -s nullglob 

    # This is shitty and need improvement
    for _state in "${state[@]}"; do
        printf '%s:\n' "${_state^}"

        for _priority in "${priority[@]}"; do
            # Reqrite this part by creating a custom sort command!
            tasks=($TODO_WORKINGDIR/$_state/$_priority/*)

            # don't print anything if empty dir
            [[ -z "${tasks[*]}" ]] && continue
            readarray -t orderedTasks < <(printf '%s\n' "${tasks[@]}" | sort -V)

            for _id in "${orderedTasks[@]}"; do
                _description="$(<"$_id/description")"
                printf '    %b. %s\n' "${color[$_priority]}${_id##*/}" "$_description"
                tput sgr0
                unset _description
            done
            unset tasks orderedTasks
        done
        printf '\n'
    done
}

show(){
    local task
    [[ -z "$HELP" ]] && _quit 2 "$HELP"
    task="$(_find "$id")" tmpFile="$(_mktemp)"
 
    [[ -z "$task" ]] && _quit 2 "Task not found!"   
    printf 'Description: \n %s\n\n' "$(<"$task"/description)" >"$tmpFile"
    printf 'Content: \n%s' "$(<"$task"/content)" >>"$tmpFile"

    ${PAGER:-less} "$tmpFile"
}

don(){
    local task
    [[ -z "$id" ]] && _quit 2 "$HELP"
    task="$(_find "$id")"

    [[ -z "$task" ]] && _quit 2 "Task not found!"
   _parse "$(_find "$id")"


    [[ -d "$TODO_WORKINGDIR/done/${priority[0]}" ]] || mkdir -p "$TODO_WORKINGDIR/done/${priority[0]}"
    mv "$task" "$TODO_WORKINGDIR/done/${priority[0]}/$id"
}

ongoing(){
    local task
    [[ -z "$id" ]] && _quit 2 "$HELP"
    task="$(_find "$id")"
    
    [[ -z "$task" ]] && _quit 2 "Task not found!"
    _parse "$(_find "$id")"


    [[ -d "$TODO_WORKINGDIR/ongoing/${priority[0]}" ]] || mkdir -p "$TODO_WORKINGDIR/ongoing/${priority[0]}"
    mv "$task" "$TODO_WORKINGDIR/ongoing/${priority[0]}/$id"
}

remove(){
    local task
    [[ -z "$id" ]] && _quit 2 "$HELP"
    task="$(_find "$id")"

    [[ -z "$task" ]] && _quit 2 "Task not found!"
    read -rp "Do you really want to remove tasks $id [yN] : " var 
    [[ "${var,}" == "y" ]] && rm -r "$task"
}

edit(){
    local task
    [[ -z "$id" ]] && _quit 2 "$HELP"
    task="$(_find "$id")"    

    [[ -z "$description" ]] || printf '%s' "$description" > "$task"/description

    ${EDITOR:-vi} "$task"/content

    [[ -z "${priority[0]}" ]] || {
        _priorityCheck "${priority[0]}"
        _priority="${priority[0]}"
        _parse "$task"
        [[ -d "$TODO_WORKINGDIR/${state[0]}/$_priority/" ]] || mkdir -p "$TODO_WORKINGDIR/${state[0]}/$_priority/"
        mv "$task" "$TODO_WORKINGDIR/${state[0]}/$_priority"
    }
}

case "$1" in
    add|list|remove|ongoing|edit|show)  method="$1";     shift          ;;
    don?)                               method="don";    shift          ;;
    *)                                  _quit 2 "$HELP"                 ;;
esac

# parse simple options, we will only accept short opts
while getopts "${OPTS}" arg; do
    case "${arg}" in
        i) id="${OPTARG}"                               ;;
        d) description="${OPTARG}"                      ;;
        s) IFS=',' read -ra state <<<"${OPTARG}"        ;;
        p) IFS=',' read -ra priority <<<"${OPTARG}"     ;;
        h) _quit 0 "$HELP"                              ;;
        ?) _quit 1 "Invalid Argument: $USAGE"           ;;
        *) _quit 1 "$USAGE"                             ;;
    esac
done
shift $((OPTIND - 1))

trap '_exit' EXIT

PATH="" type -t "$method" &>/dev/null && $method
